kotlin.code.style=official
kotlin.version=2.3.20
compose.version=1.10.1
compose.html.eap.enabled=true
systemProp.org.gradle.project.compose.html.eap.enabled=true
compose.html.eap.version=0.0.1
compose.html.eap.kotlinx-browser-common-subset.version=0.0.1+dev1
org.gradle.configuration-cache=true
org.gradle.caching=true
